#!/bin/bash
# script para iniciar infra laradoc de desenvolvimento WEB

#path laradock atalhos

work_dir=$HOME/projetos/infra/laradock-atalhos

# Laradock path Ex. $HOME/projetos/applications/laradock

path=$HOME/projetos/infra/laradock

# Laradock containers padroes que sao iniciados, voce pode ajustar comforme a sua nescessidade.

containers="mysql apache2 phpmyadmin"

case "$1" in
    "up" )
		if [ -z $2 ]
		then
			echo ""
			echo "################################################################################"
			echo "#                                                                              #"
			echo "#              INICIANDO INFRA ESTRUTURA DE DESENVOLVIMENTO WEB                #"
			echo "#                                                                              #"
			echo "################################################################################"
			echo ""
			echo "Container startados com docker-compose"
			echo "$containers"
			echo ""
			echo ""
			echo "Starting" 
			cd $path
			docker-compose up -d $containers
			echo ""
			echo "Servicos Iniciados com Sucesso"
			echo ""
			echo "Use o Comando 'laradock workspace' para acessar o container workspace"
			echo ""
			echo "User 'exit' para sair do container"
			echo ""
			exit
		else
			echo "Starting $2 Container"
			cd $path
			docker-compose up -d $2
			echo ""
			echo "Servicos Iniciados com Sucesso"
			echo ""
			echo ""
			exit
		fi 
	;;
    "down" )
		echo ""
     	echo "Desligando Infra"
		echo ""
		cd $path
        docker-compose down
		echo ""
		echo "Servicos Desligados com sucesso"
		echo ""
		echo ""
        exit
	;;
	"restart" )
		echo ""
     	echo "Reiniciando Containers"
		echo ""
		cd $path
        docker-compose restart
		echo ""
        exit
	;;

	"workspace" )
		echo ""
		echo "Acessando Workspace Container"
		echo ""
		docker exec -ti laradock_workspace_1 bash
		echo ""
		echo "saindo....OK"
		exit
	;;
	"ps" )
		echo ""
     	echo "Listando Containers"
		echo ""
		cd $path
        docker-compose ps
		echo ""
        exit
	;;
	"vhost" )
		
		cd $path/apache2/sites
		if [ -n $2 ]
		then
			#Pegando as VAriaves de host e diretorio
			vhost=$3
			diretorio=$5


			#criar vHost no apache laradock

			echo "Criando arquivo de configuracao $vhost"
			echo "
			<VirtualHost *:80>
			ServerName $vhost
			ServerAlias www.$vhost
			DocumentRoot /var/www/$diretorio
			Options Indexes FollowSymLinks

			<Directory "/var/www/$diretorio/">
				AllowOverride All
				<IfVersion < 2.4>
				Allow from all
				</IfVersion>
				<IfVersion >= 2.4>
				Require all granted
				</IfVersion>
			</Directory>

			</VirtualHost>
			" > $path/apache2/sites/$vhost.conf

			
			cat $path/apache2/sites/$vhost.conf
			echo "Vhost Criado"

			#criar registro no arquivo de hosts
			echo "Atualiando arquivo /etc/hosts"
			sudo $work_dir/updateHosts $vhost
			
		
		else 
			echo ""
			echo "Para criar um vHost voce precisa passar o host e document root do site"
			echo "Ex..: laradock vhost -h exemplo.local -d exemplo/public"
			echo ""
			
		fi
		
	;;
esac

